version: '3'

services:
  lamp_server:
    build: .
#    image: "jstormes/loopback-world"
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_autostart=1
    ports:
      - 443:443
      - 4000:3306
      - 80:80
    volumes:
      - ./:/var/www